### ISSUE TITLE
Waiting for upstream implementation of manageable GitHub topics

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/github-permissions#1]
related opentelekomcloud-infra/gitstyring/pull/30
Relevant for Team3 Story "CI dashboard tagging"

**Comment by berendt** [comment]
Implementation done. Waiting for the merge.

**Comment by berendt** [comment]
@tibeer Change is in the upstream.

**Comment by tibeer** [comment]
Great news! Closing this issue. Code has already topics included.
