### ISSUE TITLE
LICENSE is missing

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/github-permissions#19]
@tibeer you imported the code into this repository. Where does it originate from?
We need to add a proper LICENSE.

**Comment by berendt** [comment]
It's based on https://github.com/osism/github-manager. We do not yet have a LICENSE file there. Which license should we use? ASL2.0? Will add the LICENSE file there then and afterwards we can add it here as well.

**Comment by fkr** [comment]
ASL2.0 is good.

**Comment by berendt** [comment]
Added to osism/github-manager with https://github.com/osism/github-manager/commit/5f66f0e30715f4beb49bf1fb189d62559e8aa5d9.
